language: php
dist: bionic
cache:
    directories:
        - vendor
php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - 8.1
    - nightly
env:
    matrix:
        - COMPOSER_PREFER=""
        - COMPOSER_PREFER="--prefer-stable"
        - COMPOSER_PREFER="--prefer-lowest --prefer-stable"
matrix:
    allow_failures:
        -
            php: nightly
    fast_finish: true
before_script:
    - >-
        echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv
        version-name)/etc/conf.d/travis.ini
    - |
        if [ ! $(php -m | grep -ci xdebug) -eq 0 ] ; then
            phpenv config-rm xdebug.ini
        fi
    - composer update $COMPOSER_PREFER
    - |
        # We force latest atoum on php >=7
        if [ $(php -r 'echo phpversion();' | sed -e 's/\..*//g') -eq 7 ] ; then
            composer update --prefer-stable atoum/atoum
        fi
    - 'php -S 127.0.0.1:8888 -t "$TRAVIS_BUILD_DIR/www" &> /dev/null &'
script:
    - vendor/bin/atoum -ulr
    - vendor/bin/behat -f progress
